import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> 
        <div className="container min-h-screen max-sm:px-4 flex flex-col justify-center font-kanit">
          <Header />
          <main className="bg-white __mainContainer">{children}</main>
        </div>
      </body>
    </html>
  );
}
